# Generated by Django 3.0.8 on 2020-08-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabInfoETZ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_info_E', models.CharField(max_length=50)),
                ('lab_info_Z', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'lab_info_ETZs',
            },
        ),
        migrations.CreateModel(
            name='LaboratoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratory_type', models.CharField(max_length=50)),
                ('laboratory_item_label', models.CharField(max_length=100)),
                ('refer_value', models.CharField(blank=True, max_length=50, null=True)),
                ('item_unit', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'laboratory_items',
            },
        ),
        migrations.CreateModel(
            name='LaboratoryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratory_reports_id', models.IntegerField()),
                ('laboratory_items_id', models.IntegerField()),
                ('result_value', models.CharField(max_length=20)),
                ('towards', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'laboratory_logs',
            },
        ),
        migrations.CreateModel(
            name='LaboratoryReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('apply_num', models.CharField(blank=True, max_length=20, null=True)),
                ('test_order_num', models.CharField(blank=True, max_length=10, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=10, null=True)),
                ('patient_gender', models.CharField(blank=True, max_length=5, null=True)),
                ('patient_age', models.CharField(blank=True, max_length=5, null=True)),
                ('medical_record_num', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('bed_no', models.CharField(blank=True, db_column='bed_No', max_length=5, null=True)),
                ('sample_type', models.CharField(blank=True, max_length=20, null=True)),
                ('apply_time', models.DateTimeField(blank=True, null=True)),
                ('collect_time', models.DateTimeField(blank=True, null=True)),
                ('clinical_diagnosis', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_feature', models.CharField(blank=True, max_length=255, null=True)),
                ('send_doctor', models.CharField(blank=True, max_length=50, null=True)),
                ('ward', models.CharField(blank=True, max_length=50, null=True)),
                ('inspect_doctor', models.CharField(blank=True, max_length=50, null=True)),
                ('review_doctor', models.CharField(blank=True, max_length=50, null=True)),
                ('inspect_time', models.DateTimeField(blank=True, null=True)),
                ('report_time', models.DateTimeField(blank=True, null=True)),
                ('publish_time', models.DateTimeField(blank=True, null=True)),
                ('culture_result', models.CharField(blank=True, max_length=255, null=True)),
                ('culture_time', models.DateTimeField(blank=True, null=True)),
                ('is_lock', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'laboratory_reports',
            },
        ),
        migrations.CreateModel(
            name='TestSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=60)),
                ('state_province', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=50)),
                ('website', models.URLField()),
            ],
            options={
                'db_table': 'test_sheets',
            },
        ),
    ]
