# Generated by Django 2.2.15 on 2020-08-09 13:54

from django.db import migrations

def forwards_plate_func(apps, schema_editor):
    InvestigatePlate = apps.get_model("testSheets", "InvestigatePlate")
    db_alias = schema_editor.connection.alias
    InvestigatePlate.objects.using(db_alias).bulk_create([
        InvestigatePlate(id=1, plate_title="系统评估"),
        InvestigatePlate(id=2, plate_title="病因检查"),
        InvestigatePlate(id=3, plate_title="并发症"),
        InvestigatePlate(id=4, plate_title="合并症"),
    ])

def reverse_plate_func(apps, schema_editor):
    InvestigatePlate = apps.get_model("testSheets", "InvestigatePlate")
    db_alias = schema_editor.connection.alias
    InvestigatePlate.objects.using(db_alias).all().delete()

def forwards_project_func(apps, schema_editor):
    InvestigateProject = apps.get_model("testSheets", "InvestigateProject")
    db_alias = schema_editor.connection.alias
    InvestigateProject.objects.using(db_alias).bulk_create([
        InvestigateProject(id=1, investigate_plates_id=1, project_title="常规检查"),
        InvestigateProject(id=2, investigate_plates_id=2, project_title="病毒学检查"),
        InvestigateProject(id=3, investigate_plates_id=2, project_title="遗传代谢性检查"),
        InvestigateProject(id=4, investigate_plates_id=2, project_title="自身免疫性肝病"),
        InvestigateProject(id=5, investigate_plates_id=2, project_title="其他"),
        InvestigateProject(id=6, investigate_plates_id=3, project_title="感染、免疫屏障功能"),
        InvestigateProject(id=7, investigate_plates_id=3, project_title="门脉高压相关"),
        InvestigateProject(id=8, investigate_plates_id=3, project_title="肿瘤"),
        InvestigateProject(id=9, investigate_plates_id=3, project_title="代谢性脑病"),
        InvestigateProject(id=10, investigate_plates_id=3, project_title="乳酸中毒"),
        InvestigateProject(id=11, investigate_plates_id=3, project_title="肝肾综合征"),
        InvestigateProject(id=12, investigate_plates_id=4, project_title="合并症"),
    ])

def reverse_project_func(apps, schema_editor):
    InvestigateProject = apps.get_model("testSheets", "InvestigateProject")
    db_alias = schema_editor.connection.alias
    InvestigateProject.objects.using(db_alias).all().delete()

def forwards_indicator_func(apps, schema_editor):
    InvestigateIndicator = apps.get_model("testSheets", "InvestigateIndicator")
    db_alias = schema_editor.connection.alias
    InvestigateIndicator.objects.using(db_alias).bulk_create([
        InvestigateIndicator(id=1, investigate_projects_id=1, indicator_title="血常规"),
        InvestigateIndicator(id=2, investigate_projects_id=1, indicator_title="尿常规"),
        InvestigateIndicator(id=3, investigate_projects_id=1, indicator_title="大便常规"),
        InvestigateIndicator(id=4, investigate_projects_id=1, indicator_title="肝功能"),
        InvestigateIndicator(id=5, investigate_projects_id=1, indicator_title="肾功能"),
        InvestigateIndicator(id=6, investigate_projects_id=1, indicator_title="心肌酶"),
        InvestigateIndicator(id=7, investigate_projects_id=1, indicator_title="电解质"),
        InvestigateIndicator(id=8, investigate_projects_id=1, indicator_title="血糖"),
        InvestigateIndicator(id=9, investigate_projects_id=1, indicator_title="凝血功能"),
        InvestigateIndicator(id=10, investigate_projects_id=1, indicator_title="心电图"),
        InvestigateIndicator(id=11, investigate_projects_id=1, indicator_title="胸片"),
        InvestigateIndicator(id=12, investigate_projects_id=1, indicator_title="彩超"),
        InvestigateIndicator(id=13, investigate_projects_id=2, indicator_title="甲丙戊肝抗体"),
        InvestigateIndicator(id=14, investigate_projects_id=2, indicator_title="乙肝两对半定量"),
        InvestigateIndicator(id=16, investigate_projects_id=2, indicator_title="HBV DNA定量"),
        InvestigateIndicator(id=17, investigate_projects_id=2, indicator_title="病毒全套"),
        InvestigateIndicator(id=18, investigate_projects_id=2, indicator_title="EBV、CMV、HSV DNA定量"),
        InvestigateIndicator(id=19, investigate_projects_id=3, indicator_title="血清铜兰蛋白测定"),
        InvestigateIndicator(id=20, investigate_projects_id=4, indicator_title="自免肝八项"),
        InvestigateIndicator(id=21, investigate_projects_id=4, indicator_title="ANA+ENA"),
        InvestigateIndicator(id=22, investigate_projects_id=4, indicator_title="免疫全套"),
        InvestigateIndicator(id=23, investigate_projects_id=5, indicator_title="肝活检"),
        InvestigateIndicator(id=24, investigate_projects_id=6, indicator_title="内毒素"),
        InvestigateIndicator(id=25, investigate_projects_id=6, indicator_title="降钙素原"),
        InvestigateIndicator(id=26, investigate_projects_id=6, indicator_title="血沉"),
        InvestigateIndicator(id=27, investigate_projects_id=6, indicator_title="CRP"),
        InvestigateIndicator(id=28, investigate_projects_id=6, indicator_title="腹水常规"),
        InvestigateIndicator(id=29, investigate_projects_id=6, indicator_title="血培养"),
        InvestigateIndicator(id=30, investigate_projects_id=6, indicator_title="肺部CT"),
        InvestigateIndicator(id=31, investigate_projects_id=7, indicator_title="胃镜"),
        InvestigateIndicator(id=32, investigate_projects_id=8, indicator_title="AFP、异常凝血酶原"),
        InvestigateIndicator(id=33, investigate_projects_id=8, indicator_title="肝脏CT平扫+增强"),
        InvestigateIndicator(id=34, investigate_projects_id=9, indicator_title="血氨"),
        InvestigateIndicator(id=35, investigate_projects_id=10, indicator_title="血浆乳酸"),
    ])

def reverse_indicator_func(apps, schema_editor):
    InvestigateIndicator = apps.get_model("testSheets", "InvestigateIndicator")
    db_alias = schema_editor.connection.alias
    InvestigateIndicator.objects.using(db_alias).all().delete()

def forwards_item_func(apps, schema_editor):
    InvestigateItem = apps.get_model("testSheets", "InvestigateItem")
    db_alias = schema_editor.connection.alias
    InvestigateItem.objects.using(db_alias).bulk_create([
        InvestigateItem(id=1, investigate_indicators_id=1, is_shown=True, item_title="白细胞"),
        InvestigateItem(id=2, investigate_indicators_id=1, is_shown=True, item_title="血红蛋白"),
        InvestigateItem(id=3, investigate_indicators_id=1, is_shown=True, item_title="血小板"),
        InvestigateItem(id=4, investigate_indicators_id=1, is_shown=True, item_title="中性粒细胞比值"),
        InvestigateItem(id=5, investigate_indicators_id=2, is_shown=False, item_title="尿蛋白"),
        InvestigateItem(id=6, investigate_indicators_id=2, is_shown=False, item_title="尿白细胞"),
        InvestigateItem(id=7, investigate_indicators_id=2, is_shown=False, item_title="尿红细胞"),
        InvestigateItem(id=8, investigate_indicators_id=3, is_shown=False, item_title="隐血试验"),
        InvestigateItem(id=9, investigate_indicators_id=4, is_shown=True, item_title="谷丙转氨酶"),
        InvestigateItem(id=10, investigate_indicators_id=4, is_shown=True, item_title="谷草转氨酶"),
        InvestigateItem(id=11, investigate_indicators_id=4, is_shown=True, item_title="白蛋白"),
        InvestigateItem(id=12, investigate_indicators_id=4, is_shown=True, item_title="总胆红素"),
        InvestigateItem(id=13, investigate_indicators_id=4, is_shown=True, item_title="直接胆红素"),
        InvestigateItem(id=14, investigate_indicators_id=4, is_shown=True, item_title="胆汁酸"),
        InvestigateItem(id=16, investigate_indicators_id=4, is_shown=True, item_title="碱性磷酸酶"),
        InvestigateItem(id=17, investigate_indicators_id=4, is_shown=True, item_title="γ谷氨酰基转肽酶"),
        InvestigateItem(id=18, investigate_indicators_id=5, is_shown=False, item_title="尿素"),
        InvestigateItem(id=19, investigate_indicators_id=5, is_shown=False, item_title="肌酐"),
        InvestigateItem(id=20, investigate_indicators_id=5, is_shown=False, item_title="肾小球率过滤"),
        InvestigateItem(id=21, investigate_indicators_id=6, is_shown=False, item_title="肌酸激酶"),
        InvestigateItem(id=22, investigate_indicators_id=6, is_shown=False, item_title="肌酸激酶同工酶"),
        InvestigateItem(id=23, investigate_indicators_id=6, is_shown=False, item_title="乳酸脱氢酶"),
        InvestigateItem(id=24, investigate_indicators_id=7, is_shown=False, item_title="钠"),
        InvestigateItem(id=25, investigate_indicators_id=7, is_shown=False, item_title="钾"),
        InvestigateItem(id=26, investigate_indicators_id=7, is_shown=False, item_title="钙"),
        InvestigateItem(id=27, investigate_indicators_id=7, is_shown=False, item_title="磷"),
        InvestigateItem(id=28, investigate_indicators_id=9, is_shown=False, item_title="血浆凝血酶原时间"),
        InvestigateItem(id=29, investigate_indicators_id=9, is_shown=False, item_title="凝血酶原活动度"),
        InvestigateItem(id=30, investigate_indicators_id=14, is_shown=False, item_title="乙肝表面抗原定量"),
        InvestigateItem(id=31, investigate_indicators_id=16, is_shown=False, item_title="HBV DNA定量"),
        InvestigateItem(id=32, investigate_indicators_id=22, is_shown=False, item_title="IgG"),
        InvestigateItem(id=33, investigate_indicators_id=22, is_shown=False, item_title="IgM"),
        InvestigateItem(id=34, investigate_indicators_id=22, is_shown=False, item_title="IgE"),
        InvestigateItem(id=35, investigate_indicators_id=22, is_shown=False, item_title="IgA"),
        InvestigateItem(id=36, investigate_indicators_id=25, is_shown=False, item_title="降钙素原"),
        InvestigateItem(id=37, investigate_indicators_id=26, is_shown=False, item_title="血沉"),
        InvestigateItem(id=38, investigate_indicators_id=27, is_shown=False, item_title="CRP"),
        InvestigateItem(id=39, investigate_indicators_id=28, is_shown=False, item_title="细胞数总数"),
        InvestigateItem(id=40, investigate_indicators_id=28, is_shown=False, item_title="白细胞"),
        InvestigateItem(id=41, investigate_indicators_id=28, is_shown=False, item_title="多核细胞"),
        InvestigateItem(id=42, investigate_indicators_id=28, is_shown=False, item_title="ADA"),
    ])

def reverse_item_func(apps, schema_editor):
    InvestigateItem = apps.get_model("testSheets", "InvestigateItem")
    db_alias = schema_editor.connection.alias
    InvestigateItem.objects.using(db_alias).all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('testSheets', '0003_investigateindicator_investigateitem_investigateplate_investigateproject'),
    ]

    operations = [
      migrations.RunPython(forwards_plate_func, reverse_plate_func),
      migrations.RunPython(forwards_project_func, reverse_project_func),
      migrations.RunPython(forwards_indicator_func, reverse_indicator_func),
      migrations.RunPython(forwards_item_func, reverse_item_func),
    ]
