# Generated by Django 2.2.15 on 2020-08-31 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testSheets', '0004_auto_20200809_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSheetDir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=20)),
                ('medical_record_num', models.CharField(max_length=20)),
                ('dir_str', models.CharField(max_length=50)),
                ('sheet_num', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'upload_sheet_dirs',
            },
        ),
    ]
