# Generated by Django 2.2.15 on 2020-09-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testSheets', '0005_uploadsheetdir'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsheetdir',
            name='is_parsed',
            field=models.BooleanField(default=False),
        ),
    ]
